In [3]:
# ch4 - Machine Learning - 10marks
# simple linear regression
# multiple linear regression
# polynomial regression

In [4]:
# ch5 - Classification Algorithm - 12marks
# KNN
# Decision Tree

In [6]:
# ch6 - Deep Learning - 3marks mcq

# Multiple Linear Regression

In [8]:
import pandas as pd

In [10]:
# step 1 
df= pd.read_csv('car data.csv')
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0


In [12]:
# step 2 check null value
df.isna().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [13]:
#  step 3 data preprocessing
df['age']=2026-df['Year']
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,age
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,12


In [14]:
df.drop(columns='Year', inplace=True)
df.head()

,Car_Name,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,age
0,ritz,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,sx4,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,ciaz,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,wagon r,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,swift,4.60,6.87,42450,Diesel,Dealer,Manual,0,12


In [15]:
df.drop(columns='Car_Name', inplace=True)
df.head()

,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,age
0,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,4.60,6.87,42450,Diesel,Dealer,Manual,0,12


In [16]:
df= pd.get_dummies(data=df, drop_first=True)
df.head()

,Selling_Price,Present_Price,Kms_Driven,Owner,age,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,3.35,5.59,27000,0,12,False,True,False,True
1,4.75,9.54,43000,0,13,True,False,False,True
2,7.25,9.85,6900,0,9,False,True,False,True
3,2.85,4.15,5200,0,15,False,True,False,True
4,4.60,6.87,42450,0,12,True,False,False,True


In [23]:
# step 4 define x & y
y= df['Selling_Price']
x=df[['Present_Price', 'Kms_Driven', 'Owner', 'age',
       'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Individual',
       'Transmission_Manual']]

In [21]:
df.columns

Index(['Selling_Price', 'Present_Price', 'Kms_Driven', 'Owner', 'age',
       'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Individual',
       'Transmission_Manual'],
      dtype='object')

In [24]:
# step 5 split data into train & test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(240, 8)
(61, 8)
(240,)
(61,)


In [27]:
# step 6 create model
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [28]:
lr.fit(x_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [29]:
# step 7 find m & c
m=lr.coef_
m

array([ 4.29152503e-01, -6.15725866e-06, -9.03759824e-01, -3.53801365e-01,
        2.53327258e+00,  7.38464226e-01, -1.19059291e+00, -1.63902155e+00])

In [30]:
c= lr.intercept_
c

np.float64(6.848642647119797)

In [31]:
# 8 , petrol, 45000, m, indi, 0, 900000
i20_price= lr.predict([[9,45000,0,8,0,1,1,1]])
i20_price

C:\ProgramData\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.51237738])

In [32]:
# 'Present_Price', 'Kms_Driven', 'Owner', 'age', 'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Individual', 'Transmission_Manual'
# 9.54, 43000km , 0 owner, 13 age , diesel, manual, d
lr.predict([[9.54,43000,0,13,1,0,0,1]])

C:\ProgramData\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.97282868])

In [34]:
# step 8 find MSE
y_predict=lr.predict(x_test)
y_predict

array([ 2.95534303,  8.178939  ,  6.45427257, -1.42417501,  9.08889914,
        7.41825441,  1.33644285,  0.84027217,  1.36501949,  7.49026806,
        9.11830017,  0.58573931,  8.41612774,  3.42316502,  6.90043281,
        3.04988309,  0.48448171, 10.70970753,  1.75207005,  2.34571752,
        0.39746889,  8.11925338,  6.62469317,  2.65939066,  0.78280554,
        3.69330765,  5.24815462,  2.82676351,  2.13640446,  1.75237686,
        0.39730155,  9.11750503, -0.66188053,  2.29098014,  8.57067341,
        4.4910324 ,  7.20530369,  7.53824015,  2.89101139,  7.93588794,
        3.93585154,  4.27133211,  4.33205704,  0.6008847 ,  7.34025071,
        0.47602539,  7.29187681, 11.23125597,  3.13805132,  5.38262985,
        6.7988422 ,  2.17888955, 20.63303305, 17.0015261 ,  7.50717349,
        9.69621308,  4.47478116,  8.97377615,  1.82294639,  7.60416734,
        0.22226536])

In [36]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
print("MSE=",mean_squared_error(y_test,y_predict))
print("MAE=",mean_absolute_error(y_test,y_predict))
print("R2_score=",r2_score(y_test,y_predict))

MSE= 3.4788039706378613
MAE= 1.216225682129699
R2_score= 0.8489813024899084


# pb 228

In [37]:
df2= pd.read_csv('winequality.csv')
df2.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4


In [39]:
df2.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [42]:
y= df2['quality']
x=df2[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]

In [41]:
df2.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'Id'],
      dtype='object')

In [43]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [45]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(914, 11)
(229, 11)
(914,)
(229,)


In [46]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [47]:
lr.fit(x_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [48]:
m=lr.coef_
m

array([ 5.13430654e-02, -1.33625691e+00, -3.39100758e-01,  4.12143173e-03,
       -1.80653035e+00,  1.88076181e-03, -2.28305818e-03, -3.06532562e+01,
       -2.49236344e-01,  9.73040097e-01,  2.66586068e-01])

In [49]:
c= lr.intercept_
c

np.float64(34.209805578378685)

In [50]:
lr.predict([[8,0.4,0.40,15,0.048,40,150,0.99,3,0.45,10.5]])

C:\ProgramData\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.80087585])

In [51]:
y_predict=lr.predict(x_test)
y_predict

array([5.37639096, 4.81275231, 5.26822711, 5.08826518, 6.09668676,
       6.60433542, 5.36417303, 5.06978794, 5.78461148, 5.32382095,
       6.31298023, 6.39721516, 5.3122581 , 6.20451475, 5.86121236,
       4.84318641, 5.69306745, 5.70473751, 5.50099506, 6.4022271 ,
       6.06476494, 6.03726349, 5.17366124, 6.50195777, 5.60352313,
       5.10641179, 6.56067549, 5.96071079, 5.10316054, 5.57954028,
       6.20303322, 5.47600319, 6.59869683, 5.73347337, 5.55058293,
       5.26541133, 5.48831034, 6.05771316, 6.95448756, 6.57961946,
       6.4526993 , 5.34213598, 7.03445013, 5.37970557, 5.05503642,
       5.0554158 , 5.61860118, 5.8525548 , 4.63668652, 5.68553779,
       6.42194262, 5.26381661, 5.60884518, 5.88146705, 5.78923411,
       6.38843403, 5.50237456, 5.70598277, 6.0421496 , 5.23069794,
       5.52701136, 5.95270183, 5.60755482, 6.35884408, 6.15031671,
       5.38044967, 6.86150613, 5.26208169, 4.8615088 , 5.98738066,
       5.74523457, 5.33651712, 5.93642512, 5.94447105, 5.18598

In [52]:
print("MSE=",mean_squared_error(y_test,y_predict))

MSE= 0.38003245026277577


# PB 226

In [53]:
df3= pd.read_csv('RealEstate.csv')
df3.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1


In [55]:
df3.isna().sum()

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [56]:
df3.columns

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [59]:
df3.drop(columns='No', inplace=True)
df3.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1


In [60]:
y=df3['Y house price of unit area']
x=df3[['X1 transaction date', 'X2 house age','X3 distance to the nearest MRT station', 'X4 number of convenience stores', 'X5 latitude', 'X6 longitude']]

In [72]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=110)

In [73]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(289, 6)
(125, 6)
(289,)
(125,)


In [74]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [75]:
lr.fit(x_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [76]:
y_predict=lr.predict(x_test)
y_predict

array([40.06913335, 32.56470479, 29.80668902, 44.60809493, 39.96541473,
       44.34984726, 37.64834639, 51.18801909, 37.08044432, 38.64449437,
       36.45757424, 31.64776451, 43.03392987, 16.64984039, 36.61381207,
       31.21699197, 39.55333345, 41.89770923, 46.41953538, 42.69067202,
       40.49560609, 53.3447345 , 40.74436408, 36.67049204, 46.86499408,
       42.78349352, 47.25115307, 40.53653503, 42.57499139, 50.88772177,
       44.81813044, 41.05114011, 35.39386877, 42.95199941, 13.97578058,
       30.00463214,  0.32863779, 39.56884707, 47.9626967 , 34.0147913 ,
       40.23322474, 49.74492584, 36.73990519, 35.39784888, 29.6071314 ,
       45.83432319, 42.44745248, 37.88237609, 31.55675944, 47.517238  ,
       35.03089266, 45.17666152, 45.98711652, 47.32685806, 54.18178829,
       15.18888047, 43.78264851, 44.75385635, 37.69057227, 39.34215811,
       44.21812376, 44.27270068, 47.84570949, 38.42626454, 41.0626191 ,
       19.64522484, 47.9626967 , 43.85961508, 37.99756745, 43.80

In [77]:
print("MSE=",mean_squared_error(y_test,y_predict))

MSE= 77.14802598253691


# PB 227

In [87]:
df4 = pd.read_csv('insurance.csv')
df4.head()

,age,sex,bmi,children,smoker,region,expenses
0,19,female,27.9,0,yes,southwest,16884.92
1,18,male,33.8,1,no,southeast,1725.55
2,28,male,33.0,3,no,southeast,4449.46
3,33,male,22.7,0,no,northwest,21984.47
4,32,male,28.9,0,no,northwest,3866.86


In [88]:
df4=pd.get_dummies(data=df4, drop_first = True)
df4.head()

,age,bmi,children,expenses,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.9,0,16884.92,False,True,False,False,True
1,18,33.8,1,1725.55,True,False,False,True,False
2,28,33.0,3,4449.46,True,False,False,True,False
3,33,22.7,0,21984.47,True,False,True,False,False
4,32,28.9,0,3866.86,True,False,True,False,False


In [89]:
df4.isna().sum()

age                 0
bmi                 0
children            0
expenses            0
sex_male            0
smoker_yes          0
region_northwest    0
region_southeast    0
region_southwest    0
dtype: int64

In [90]:
df4.columns

Index(['age', 'bmi', 'children', 'expenses', 'sex_male', 'smoker_yes',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='object')

In [95]:
y=df4['expenses']
x=df4[['age', 'bmi', 'children', 'sex_male', 'smoker_yes',
       'region_northwest', 'region_southeast', 'region_southwest']]

In [96]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [97]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1070, 8)
(268, 8)
(1070,)
(268,)


In [98]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [99]:
lr.fit(x_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [101]:
lr.predict([[31,21.5,2,0,1,0,0,0]])

C:\ProgramData\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([27781.79203199])